import CypherLexer from './generated-parser/CypherLexer';

export enum CypherTokenType {
  comment = 'comment',
  keyword = 'keyword',
  label = 'label',
  predicateFunction = 'predicateFunction',
  function = 'function',
  procedure = 'procedure',
  variable = 'variable',
  paramDollar = 'paramDollar',
  paramValue = 'paramValue',
  symbolicName = 'symbolicName',
  operator = 'operator',
  stringLiteral = 'stringLiteral',
  numberLiteral = 'numberLiteral',
  booleanLiteral = 'booleanLiteral',
  keywordLiteral = 'keywordLiteral',
  property = 'property',
  namespace = 'namespace',
  bracket = 'bracket',
  none = 'none',
}

export const lexerSymbols: Record<number, CypherTokenType> = {
  [CypherLexer.ACCESS]: CypherTokenType.keyword,
  [CypherLexer.ACTIVE]: CypherTokenType.keyword,
  [CypherLexer.ADMIN]: CypherTokenType.keyword,
  [CypherLexer.ADMINISTRATOR]: CypherTokenType.keyword,
  [CypherLexer.ALIAS]: CypherTokenType.keyword,
  [CypherLexer.ALIASES]: CypherTokenType.keyword,
  [CypherLexer.ALL_SHORTEST_PATH]: CypherTokenType.keyword,
  [CypherLexer.ALL]: CypherTokenType.keyword,
  [CypherLexer.ALTER]: CypherTokenType.keyword,
  [CypherLexer.AND]: CypherTokenType.keyword,
  [CypherLexer.ANY]: CypherTokenType.keyword,
  [CypherLexer.AS]: CypherTokenType.keyword,
  [CypherLexer.ASC]: CypherTokenType.keyword,
  [CypherLexer.ASSERT]: CypherTokenType.keyword,
  [CypherLexer.ASSIGN]: CypherTokenType.keyword,
  [CypherLexer.AT]: CypherTokenType.keyword,
  [CypherLexer.BAR]: CypherTokenType.operator,
  [CypherLexer.BOOSTED]: CypherTokenType.keyword,
  [CypherLexer.BREAK]: CypherTokenType.keyword,
  [CypherLexer.BRIEF]: CypherTokenType.keyword,
  [CypherLexer.BTREE]: CypherTokenType.keyword,
  [CypherLexer.BUILT]: CypherTokenType.keyword,
  [CypherLexer.BY]: CypherTokenType.keyword,
  [CypherLexer.CALL]: CypherTokenType.keyword,
  [CypherLexer.CASE]: CypherTokenType.keyword,
  [CypherLexer.CHANGE]: CypherTokenType.keyword,
  [CypherLexer.COLON]: CypherTokenType.operator,
  [CypherLexer.COMMA]: CypherTokenType.operator,
  [CypherLexer.COMMAND]: CypherTokenType.keyword,
  [CypherLexer.COMMANDS]: CypherTokenType.keyword,
  [CypherLexer.COMMIT]: CypherTokenType.keyword,
  [CypherLexer.COMPOSITE]: CypherTokenType.keyword,
  [CypherLexer.CONSTRAINT]: CypherTokenType.keyword,
  [CypherLexer.CONSTRAINTS]: CypherTokenType.keyword,
  [CypherLexer.CONTAINS]: CypherTokenType.keyword,
  [CypherLexer.COPY]: CypherTokenType.keyword,
  [CypherLexer.CONTINUE]: CypherTokenType.keyword,
  [CypherLexer.COUNT]: CypherTokenType.keyword,
  [CypherLexer.CREATE]: CypherTokenType.keyword,
  [CypherLexer.CSV]: CypherTokenType.keyword,
  [CypherLexer.CURRENT]: CypherTokenType.keyword,
  [CypherLexer.DATA]: CypherTokenType.keyword,
  [CypherLexer.DATABASE]: CypherTokenType.keyword,
  [CypherLexer.DATABASES]: CypherTokenType.keyword,
  [CypherLexer.DBMS]: CypherTokenType.keyword,
  [CypherLexer.DEALLOCATE]: CypherTokenType.keyword,
  [CypherLexer.DEFAULT_TOKEN]: CypherTokenType.keyword,
  [CypherLexer.DEFINED]: CypherTokenType.keyword,
  [CypherLexer.DELETE]: CypherTokenType.keyword,
  [CypherLexer.DENY]: CypherTokenType.keyword,
  [CypherLexer.DESC]: CypherTokenType.keyword,
  [CypherLexer.DESTROY]: CypherTokenType.keyword,
  [CypherLexer.DETACH]: CypherTokenType.keyword,
  [CypherLexer.DOLLAR]: CypherTokenType.operator,
  [CypherLexer.DISTINCT]: CypherTokenType.keyword,
  [CypherLexer.DIVIDE]: CypherTokenType.operator,
  [CypherLexer.DOT]: CypherTokenType.operator,
  [CypherLexer.DOTDOT]: CypherTokenType.operator,
  [CypherLexer.DRIVER]: CypherTokenType.keyword,
  [CypherLexer.DROP]: CypherTokenType.keyword,
  [CypherLexer.DRYRUN]: CypherTokenType.keyword,
  [CypherLexer.DUMP]: CypherTokenType.keyword,
  [CypherLexer.EACH]: CypherTokenType.keyword,
  [CypherLexer.ENABLE]: CypherTokenType.keyword,
  [CypherLexer.ELEMENT]: CypherTokenType.keyword,
  [CypherLexer.ELEMENTS]: CypherTokenType.keyword,
  [CypherLexer.ELSE]: CypherTokenType.keyword,
  [CypherLexer.ENCRYPTED]: CypherTokenType.keyword,
  [CypherLexer.END]: CypherTokenType.keyword,
  [CypherLexer.ENDS]: CypherTokenType.keyword,
  [CypherLexer.EQ]: CypherTokenType.operator,
  [CypherLexer.EXECUTABLE]: CypherTokenType.keyword,
  [CypherLexer.EXECUTE]: CypherTokenType.keyword,
  [CypherLexer.EXIST]: CypherTokenType.keyword,
  [CypherLexer.EXISTENCE]: CypherTokenType.keyword,
  [CypherLexer.EXISTS]: CypherTokenType.keyword,
  [CypherLexer.ERROR]: CypherTokenType.keyword,
  [CypherLexer.FAIL]: CypherTokenType.keyword,
  [CypherLexer.FALSE]: CypherTokenType.keyword,
  [CypherLexer.FIELDTERMINATOR]: CypherTokenType.keyword,
  [CypherLexer.FOR]: CypherTokenType.keyword,
  [CypherLexer.FOREACH]: CypherTokenType.keyword,
  [CypherLexer.FROM]: CypherTokenType.keyword,
  [CypherLexer.FULLTEXT]: CypherTokenType.keyword,
  [CypherLexer.FUNCTION]: CypherTokenType.keyword,
  [CypherLexer.FUNCTIONS]: CypherTokenType.keyword,
  [CypherLexer.GE]: CypherTokenType.operator,
  [CypherLexer.GRANT]: CypherTokenType.keyword,
  [CypherLexer.GRAPH]: CypherTokenType.keyword,
  [CypherLexer.GRAPHS]: CypherTokenType.keyword,
  [CypherLexer.GT]: CypherTokenType.operator,
  [CypherLexer.HEADERS]: CypherTokenType.keyword,
  [CypherLexer.HOME]: CypherTokenType.keyword,
  [CypherLexer.IF]: CypherTokenType.keyword,
  [CypherLexer.IMPERSONATE]: CypherTokenType.keyword,
  [CypherLexer.IMMUTABLE]: CypherTokenType.keyword,
  [CypherLexer.IN]: CypherTokenType.keyword,
  [CypherLexer.INDEX]: CypherTokenType.keyword,
  [CypherLexer.INDEXES]: CypherTokenType.keyword,
  [CypherLexer.INF]: CypherTokenType.keyword,
  [CypherLexer.INFINITY]: CypherTokenType.keyword,
  [CypherLexer.IS]: CypherTokenType.keyword,
  [CypherLexer.JOIN]: CypherTokenType.keyword,
  [CypherLexer.KEY]: CypherTokenType.keyword,
  [CypherLexer.LABEL]: CypherTokenType.keyword,
  [CypherLexer.LABELS]: CypherTokenType.keyword,
  [CypherLexer.AMPERSAND]: CypherTokenType.operator,
  [CypherLexer.EXCLAMATION_MARK]: CypherTokenType.operator,
  [CypherLexer.LBRACKET]: CypherTokenType.bracket,
  [CypherLexer.LCURLY]: CypherTokenType.bracket,
  [CypherLexer.LE]: CypherTokenType.operator,
  [CypherLexer.LIMITROWS]: CypherTokenType.keyword,
  [CypherLexer.LOAD]: CypherTokenType.keyword,
  [CypherLexer.LOOKUP]: CypherTokenType.keyword,
  [CypherLexer.LPAREN]: CypherTokenType.bracket,
  [CypherLexer.LT]: CypherTokenType.operator,
  [CypherLexer.MANAGEMENT]: CypherTokenType.keyword,
  [CypherLexer.MATCH]: CypherTokenType.keyword,
  [CypherLexer.MERGE]: CypherTokenType.keyword,
  [CypherLexer.MINUS]: CypherTokenType.operator,
  [CypherLexer.PERCENT]: CypherTokenType.operator,
  [CypherLexer.NEQ]: CypherTokenType.operator,
  [CypherLexer.NEQ2]: CypherTokenType.operator,
  [CypherLexer.NAME]: CypherTokenType.keyword,
  [CypherLexer.NAMES]: CypherTokenType.keyword,
  [CypherLexer.NAN]: CypherTokenType.keyword,
  [CypherLexer.NEW]: CypherTokenType.keyword,
  [CypherLexer.NODE]: CypherTokenType.keyword,
  [CypherLexer.NODES]: CypherTokenType.keyword,
  [CypherLexer.NONE]: CypherTokenType.keyword,
  [CypherLexer.NOT]: CypherTokenType.keyword,
  [CypherLexer.NOWAIT]: CypherTokenType.keyword,
  [CypherLexer.NULL]: CypherTokenType.keyword,
  [CypherLexer.OF]: CypherTokenType.keyword,
  [CypherLexer.ON]: CypherTokenType.keyword,
  [CypherLexer.ONLY]: CypherTokenType.keyword,
  [CypherLexer.OPTIONAL]: CypherTokenType.keyword,
  [CypherLexer.OPTIONS]: CypherTokenType.keyword,
  [CypherLexer.OPTION]: CypherTokenType.keyword,
  [CypherLexer.OR]: CypherTokenType.keyword,
  [CypherLexer.ORDER]: CypherTokenType.keyword,
  [CypherLexer.OUTPUT]: CypherTokenType.keyword,
  [CypherLexer.PASSWORD]: CypherTokenType.keyword,
  [CypherLexer.PASSWORDS]: CypherTokenType.keyword,
  [CypherLexer.PERIODIC]: CypherTokenType.keyword,
  [CypherLexer.PLAINTEXT]: CypherTokenType.keyword,
  [CypherLexer.PLUS]: CypherTokenType.operator,
  [CypherLexer.PLUSEQUAL]: CypherTokenType.operator,
  [CypherLexer.POINT]: CypherTokenType.keyword,
  [CypherLexer.POPULATED]: CypherTokenType.keyword,
  [CypherLexer.POW]: CypherTokenType.keyword,
  [CypherLexer.PRIMARY]: CypherTokenType.keyword,
  [CypherLexer.PRIMARIES]: CypherTokenType.keyword,
  [CypherLexer.PRIVILEGE]: CypherTokenType.keyword,
  [CypherLexer.PRIVILEGES]: CypherTokenType.keyword,
  [CypherLexer.PROCEDURE]: CypherTokenType.keyword,
  [CypherLexer.PROCEDURES]: CypherTokenType.keyword,
  [CypherLexer.PROPERTIES]: CypherTokenType.keyword,
  [CypherLexer.PROPERTY]: CypherTokenType.keyword,
  [CypherLexer.QUESTION]: CypherTokenType.operator,
  [CypherLexer.RANGE]: CypherTokenType.keyword,
  [CypherLexer.RBRACKET]: CypherTokenType.bracket,
  [CypherLexer.RCURLY]: CypherTokenType.bracket,
  [CypherLexer.READ]: CypherTokenType.keyword,
  [CypherLexer.REALLOCATE]: CypherTokenType.keyword,
  [CypherLexer.REDUCE]: CypherTokenType.keyword,
  [CypherLexer.RENAME]: CypherTokenType.keyword,
  [CypherLexer.REGEQ]: CypherTokenType.operator,
  [CypherLexer.REL]: CypherTokenType.keyword,
  [CypherLexer.RELATIONSHIP]: CypherTokenType.keyword,
  [CypherLexer.RELATIONSHIPS]: CypherTokenType.keyword,
  [CypherLexer.REMOVE]: CypherTokenType.keyword,
  [CypherLexer.REPLACE]: CypherTokenType.keyword,
  [CypherLexer.REPORT]: CypherTokenType.keyword,
  [CypherLexer.REQUIRE]: CypherTokenType.keyword,
  [CypherLexer.REQUIRED]: CypherTokenType.keyword,
  [CypherLexer.RETURN]: CypherTokenType.keyword,
  [CypherLexer.REVOKE]: CypherTokenType.keyword,
  [CypherLexer.ROLE]: CypherTokenType.keyword,
  [CypherLexer.ROLES]: CypherTokenType.keyword,
  [CypherLexer.ROW]: CypherTokenType.keyword,
  [CypherLexer.ROWS]: CypherTokenType.keyword,
  [CypherLexer.RPAREN]: CypherTokenType.bracket,
  [CypherLexer.SCAN]: CypherTokenType.keyword,
  [CypherLexer.SEC]: CypherTokenType.keyword,
  [CypherLexer.SECOND]: CypherTokenType.keyword,
  [CypherLexer.SECONDARY]: CypherTokenType.keyword,
  [CypherLexer.SECONDARIES]: CypherTokenType.keyword,
  [CypherLexer.SECONDS]: CypherTokenType.keyword,
  [CypherLexer.SEEK]: CypherTokenType.keyword,
  [CypherLexer.SEMICOLON]: CypherTokenType.operator,
  [CypherLexer.SERVER]: CypherTokenType.keyword,
  [CypherLexer.SERVERS]: CypherTokenType.keyword,
  [CypherLexer.SET]: CypherTokenType.keyword,
  [CypherLexer.SETTING]: CypherTokenType.keyword,
  [CypherLexer.SETTINGS]: CypherTokenType.keyword,
  [CypherLexer.SHORTEST_PATH]: CypherTokenType.keyword,
  [CypherLexer.SHOW]: CypherTokenType.keyword,
  [CypherLexer.SINGLE]: CypherTokenType.keyword,
  [CypherLexer.SKIPROWS]: CypherTokenType.keyword,
  [CypherLexer.START]: CypherTokenType.keyword,
  [CypherLexer.STARTS]: CypherTokenType.keyword,
  [CypherLexer.STATUS]: CypherTokenType.keyword,
  [CypherLexer.STOP]: CypherTokenType.keyword,
  [CypherLexer.SUSPENDED]: CypherTokenType.keyword,
  [CypherLexer.TARGET]: CypherTokenType.keyword,
  [CypherLexer.TERMINATE]: CypherTokenType.keyword,
  [CypherLexer.TEXT]: CypherTokenType.keyword,
  [CypherLexer.THEN]: CypherTokenType.keyword,
  [CypherLexer.TIMES]: CypherTokenType.operator,
  [CypherLexer.TO]: CypherTokenType.keyword,
  [CypherLexer.TOPOLOGY]: CypherTokenType.keyword,
  [CypherLexer.TRANSACTION]: CypherTokenType.keyword,
  [CypherLexer.TRANSACTIONS]: CypherTokenType.keyword,
  [CypherLexer.TRAVERSE]: CypherTokenType.keyword,
  [CypherLexer.TRUE]: CypherTokenType.keyword,
  [CypherLexer.TYPE]: CypherTokenType.keyword,
  [CypherLexer.TYPES]: CypherTokenType.keyword,
  [CypherLexer.UNION]: CypherTokenType.keyword,
  [CypherLexer.UNIQUE]: CypherTokenType.keyword,
  [CypherLexer.UNIQUENESS]: CypherTokenType.keyword,
  [CypherLexer.UNWIND]: CypherTokenType.keyword,
  [CypherLexer.USE]: CypherTokenType.keyword,
  [CypherLexer.USER]: CypherTokenType.keyword,
  [CypherLexer.USERS]: CypherTokenType.keyword,
  [CypherLexer.USING]: CypherTokenType.keyword,
  [CypherLexer.VERBOSE]: CypherTokenType.keyword,
  [CypherLexer.WAIT]: CypherTokenType.keyword,
  [CypherLexer.WHEN]: CypherTokenType.keyword,
  [CypherLexer.WHERE]: CypherTokenType.keyword,
  [CypherLexer.WITH]: CypherTokenType.keyword,
  [CypherLexer.WRITE]: CypherTokenType.keyword,
  [CypherLexer.XOR]: CypherTokenType.keyword,
  [CypherLexer.YIELD]: CypherTokenType.keyword,
};
