name: 'Codemirror E2E tests'
inputs:
  browser:
    description: 'Browser to run tests (chromium or firefox)'
    required: true
    default: 'chromium'

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

runs:
  using: 'composite'
  steps:
    - name: Validate browser input
      shell: bash
      run: |
        if [[ "${{ inputs.browser }}" != "chromium" && "${{ inputs.browser }}" != "firefox" ]]; then
          echo "Invalid browser (should be one of firefox or chromium): ${{ inputs.browser }}"
          exit 1
        fi
    
    - name: Install Playwright Browsers
      shell: bash
      run: pnpm exec playwright install --only-shell --with-deps ${{ inputs.browser }}
      working-directory: packages/react-codemirror

    - name: List files
      shell: bash
      run: |
        ls packages/react-codemirror/dist/src/lang-cypher
        ls packages/react-codemirror/src/lang-cypher
    
    - name: Run e2e test
      shell: bash
      run: pnpm --filter react-codemirror test:e2e --project=${{ inputs.browser }}

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ inputs.browser }}
        path: packages/react-codemirror/playwright-report/
        retention-days: 30