name: 'Setups antlr4 manually'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        curl https://www.antlr.org/download/antlr-4.13.0-complete.jar --output antlr4.jar
        mkdir -p $HOME/.local/bin
        echo -e "#bin/bash\njava -jar $PWD/antlr4.jar \$@" > $HOME/.local/bin/antlr4
        chmod a+x $HOME/.local/bin/antlr4
