on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

jobs:
  archive-vscode-artifacts:
    name: Archives VSCode artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup project
        uses: ./.github/actions/setup-and-build

      - name: Generate VSCode plugin package
        run: |
          cd packages/vscode-extension
          pnpm package

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: vscode-extension
          path: packages/vscode-extension/*.vsix
          retention-days: 30
