name: Push benchmarks to grafana

on:
  push:
    branches: [main]

jobs:
  benchmark:
    name: Time benchmark
    environment: grafana-api-key
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --only-shell --with-deps
        working-directory: packages/react-codemirror

      - name: Benchmark
        run: pnpm benchmark --concurrency=1
