name: Push benchmarks to grafana

on:
  push:
    branches: [main]

jobs:
  benchmark:
    name: Time benchmark
    environment: grafana-api-key
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --only-shell --with-deps
        working-directory: packages/react-codemirror

      - name: Benchmark
        run: pnpm benchmark --concurrency=1
