on:
  push:
    branches:
      - main
    paths:
      - 'packages/language-support/src/formatting/**'

  pull_request:
    branches:
      - main
    paths:
      - 'packages/language-support/src/formatting/**'

jobs:
  formatting-integrity-check:
    name: Formatter integrity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup antlr4
        uses: ./.github/actions/setup-antlr4

      - name: Install dependencies with frozen lock file and generate parser
        run: npm ci

      - name: Build Project
        run: pnpm build

      - name: Run formatting check
        run: pnpm test:formattingIntegrity
