name: Publish packages to npm

on:
  workflow_run:
    workflows: ['ci']
    branches: ['main']
    types:
      - completed

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  canary-release-to-npm:
    name: 'Canary release to npm'
    if: github.event.workflow_run.conclusion == 'success'
    needs: stable-release-to-npm
    environment: publish-npm
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Build and release canary package to npm
        run: pnpm snapshot-release

  stable-release-to-npm:
    name: 'Stable release to npm'
    if: github.event.workflow_run.conclusion == 'success'
    environment: publish-npm
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ''
