name: Publish VSCode extension to Marketplace and OpenVSX

on:
  workflow_dispatch:
  push:
    tags:
      - 'neo4j-for-vscode@*.*.*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  NODE_OPTIONS: '--max_old_space_size=8192'

jobs:
  publish-vscode-extension:
    name: 'Publish VSCode extension to Marketplace and OpenVSX'
    environment: publish-vscode-extension
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Publish to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          cd packages/vscode-extension
          pnpm package
          pnpm vsce publish --no-dependencies

      - name: Publish to OpenVSX
        env:
          VSX_PAT: ${{ secrets.VSX_PAT }}
        run: |
          cd packages/vscode-extension
          pnpm ovsx publish -p $VSX_PAT --no-dependencies
