name: Publish packages to npm

on:
  workflow_run:
    workflows: ['ci']
    branches: ['main']
    types:
      - completed

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  canary-release-to-npm:
    name: 'Canary release to npm'
    needs: stable-release-to-npm
    environment: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Build and release canary package to npm
        run: pnpm snapshot-release

  stable-release-to-npm:
    name: 'Stable release to npm'
    environment: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ''
