name: Publish canary packages to npm

# configure manual trigger
on:
  workflow_dispatch:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  canary-release-to-npm:
    name: 'Stable release to npm'
    environment: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup antlr4
        uses: ./.github/actions/setup-antlr4

      - name: Install dependencies with frozen lock file and generate parser
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Release canary to npm
        run: node ./release-canary.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
